### ISSUE TITLE
Issue when using Matomo Analytics combined with Tag Manager

### ISSUE THREAD

**Issue by jurgen-reconcept** [matomo-org/tag-manager#172]
Since last week our web app suddenly stopped working due to an error in Tag Manager, even though on our end nothing changed after successfully using it for a few months.

I already figured out that the problem **only** occurs if I'm importing both the matomo.js script and the /js/container_{id}.js file. I get the following error:

```
Error: A siteId must be given to add a new tracker
    at Q.addTracker (matomo.js:63) [angular]
    at Object.addTracker (matomo.js:74) [angular]
    at reconcept.matomo.cloud/js/container_fLyk0WXk.js:228:333 [angular]
    at Object.push (container_fLyk0WXk.js:38) [angular]
    at Object.fire (container_fLyk0WXk.js:227) [angular]
    at g._doFire (container_fLyk0WXk.js:31) [angular]
    at g.fire (container_fLyk0WXk.js:31) [angular]
    at xxx.matomo.cloud/js/container_fLyk0WXk.js:28:737 [angular]
    at Array.<anonymous> (container_fLyk0WXk.js:255) [angular]
    at t.push (container_fLyk0WXk.js:16) [angular]
    at n.onNewGlobalDataLayerValue (container_fLyk0WXk.js:32) [angular]
    at Array.<anonymous> (container_fLyk0WXk.js:32) [angular]
    at t.push (container_fLyk0WXk.js:16) [angular]
    at Object.push (container_fLyk0WXk.js:35) [angular]
```

I have no clue as to what this means. I can't seem to find any similar issues online.

**Comment by tsteur** [comment]
I remember there was a similar question here (in German): https://forum.matomo.org/t/bestehende-tracking-in-tag-manager-verwenden/31644/5

We do not recommend including both the tag manager and embedding the regular Matomo tag. 

* If you want to create a separate tracker manually, I would recommend removing the part from the tracking code that loads the `matomo.js`. 
* Alternatively, you can disable the bundling of the Matomo JS Tracker in the `Matomo Configuration` variable:
![image](https://user-images.githubusercontent.com/273120/62246703-58a6b780-b438-11e9-934c-a1dd634d3cde.png)

This might do the trick as well. Be great to let us know if any of those 2 ways work for you.

Alternatively, be great if you could share a URL where we can reproduce this. You could even email us at hello at matomo.org
